version: '3.8'

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
services:
  db-pg:
    container_name: db-pg
    image: bitnami/postgresql
    ports:
      - ${POSTGRESSQL_PORT}:${POSTGRESSQL_PORT}
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}',
        ]
      interval: 2s
      timeout: 2s
      retries: 50
  redis:
    container_name: redis
    image: redis:7.4.2-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
